### PR TITLE
Adding BesterArmor

### PR DESCRIPTION
**Pull request by clone2204**
Get some BesterArmor Yall

### CODE REVIEW

**Comment by ttk2** [comment]
you just copied and pasted your plugin into another plugin...... there is a
reason BergyPVP uses a humbug style interface, each subfunction works well
as part of the whole and its heavily configurable and extensible live, you
can't just run roughshod over that expect us to be fine with it, I know best practice is hard and time consuming, but its well worth it down the line.

**Comment by clone2204** [comment]
I'm sorry, I am not a professional developer, I don't really know all the
best practices like berge does. This is literally the first time I have
played with bukkit. I don't really know how I am supposed to put it into
bergePVP any other way than the way I did.

On Sat, May 23, 2015 at 8:03 AM, ttk2 notifications@github.com wrote:

> you just copied and pasted your plugin into another plugin...... there is a
> reason BergyPVP uses a humbug style interface, each subfunction works well
> as part of the whole and its heavily configurable and extensible live, you
> can't just run roughshod over that expect us to be fine with it, when I
> said I needed this in BergyPVP I mean't I wanted it to have all the
> advantages and best practice considerations BergyPVP did, this is just a
> stupid hack.
> 
> On Fri, May 22, 2015 at 11:41 PM clone2204 notifications@github.com
> wrote:
> 
> > ## Get some BesterArmor Yall
> > 
> > You can view, comment on, or merge this pull request online at:
> > 
> > https://github.com/Civcraft/Bergeypvp/pull/5
> > Commit Summary
> > - BesterArmor
> > - Remove Eclipse crap
> > - Final Commit
> > - Final Remove Stupid Eclipse Shit
> > 
> > File Changes
> > - _M_ src/com/valadian/bergecraft/BergeyPvp.java
> >   https://github.com/Civcraft/Bergeypvp/pull/5/files#diff-0 (101)
> > - _A_ src/com/valadian/bergecraft/besterarmor/ArmorData.java
> >   https://github.com/Civcraft/Bergeypvp/pull/5/files#diff-1 (137)
> > - _A_
> >   src/com/valadian/bergecraft/besterarmor/ExtendedInventorySaver.java
> >   https://github.com/Civcraft/Bergeypvp/pull/5/files#diff-2 (215)
> > - _A_
> >   src/com/valadian/bergecraft/besterarmor/Listeners/ArmorListener.java
> >   https://github.com/Civcraft/Bergeypvp/pull/5/files#diff-3 (143)
> > - _A_
> >   src/com/valadian/bergecraft/besterarmor/Listeners/DecloakListener.java
> >   https://github.com/Civcraft/Bergeypvp/pull/5/files#diff-4 (143)
> > - _A_
> >   src/com/valadian/bergecraft/besterarmor/Listeners/HorseMountListener.java
> >   https://github.com/Civcraft/Bergeypvp/pull/5/files#diff-5 (49)
> > - _A_
> >   src/com/valadian/bergecraft/besterarmor/Managers/ArmorManager.java
> >   https://github.com/Civcraft/Bergeypvp/pull/5/files#diff-6 (306)
> > 
> > Patch Links:
> > - https://github.com/Civcraft/Bergeypvp/pull/5.patch
> > - https://github.com/Civcraft/Bergeypvp/pull/5.diff
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Civcraft/Bergeypvp/pull/5.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Civcraft/Bergeypvp/pull/5#issuecomment-104892191.

## 

Thank You,
Will Jackins

**Comment by ttk2** [comment]
I am sorry for being so harsh then, you pumped this out pretty quickly,
that's really impressive if you are new to programming. I will try and
rally some devs to explain to you how the humbug architecture that BergyPVP
uses works, why its good, and how to work with it, I have no doubt you can
get the stuff in there the right way, its really not even that much more
effort (at lot of little change that go a long way).

**Comment by clone2204** [comment]
I am not really new to programming, just new to bukkit, and I know nothing
about humbug. So yea, if you could get someone to tell me what I need to do
to get what you are looking for, I will work on it and hopefully get you a
working version soon.

On Sat, May 23, 2015 at 4:38 PM, ttk2 notifications@github.com wrote:

> I am sorry for being so harsh then, you pumped this out pretty quickly,
> that's really impressive if you are new to programming. I will try and
> rally some devs to explain to you how the humbug architecture that BergyPVP
> uses works, why its good, and how to work with it, I have no doubt you can
> get the stuff in there the right way, its really not even that much more
> effort (at lot of little change that go a long way).
> 
> On Sat, May 23, 2015 at 4:34 PM clone2204 notifications@github.com
> wrote:
> 
> > I'm sorry, I am not a professional developer, I don't really know all the
> > best practices like berge does. This is literally the first time I have
> > played with bukkit. I don't really know how I am supposed to put it into
> > bergePVP any other way than the way I did.
> > 
> > On Sat, May 23, 2015 at 8:03 AM, ttk2 notifications@github.com wrote:
> > 
> > > you just copied and pasted your plugin into another plugin...... there
> > > is a
> > > reason BergyPVP uses a humbug style interface, each subfunction works
> > > well
> > > as part of the whole and its heavily configurable and extensible live,
> > > you
> > > can't just run roughshod over that expect us to be fine with it, when I
> > > said I needed this in BergyPVP I mean't I wanted it to have all the
> > > advantages and best practice considerations BergyPVP did, this is just
> > > a
> > > stupid hack.
> > > 
> > > On Fri, May 22, 2015 at 11:41 PM clone2204 notifications@github.com
> > > wrote:
> > > 
> > > > ## Get some BesterArmor Yall
> > > > 
> > > > You can view, comment on, or merge this pull request online at:
> > > > 
> > > > https://github.com/Civcraft/Bergeypvp/pull/5
> > > > Commit Summary
> > > > - BesterArmor
> > > > - Remove Eclipse crap
> > > > - Final Commit
> > > > - Final Remove Stupid Eclipse Shit
> > > > 
> > > > File Changes
> > > > - _M_ src/com/valadian/bergecraft/BergeyPvp.java
> > > >   https://github.com/Civcraft/Bergeypvp/pull/5/files#diff-0 (101)
> > > > - _A_ src/com/valadian/bergecraft/besterarmor/ArmorData.java
> > > >   https://github.com/Civcraft/Bergeypvp/pull/5/files#diff-1 (137)
> > > > - _A_
> > > >   src/com/valadian/bergecraft/besterarmor/ExtendedInventorySaver.java
> > > >   https://github.com/Civcraft/Bergeypvp/pull/5/files#diff-2 (215)
> > > > - _A_
> > > >   src/com/valadian/bergecraft/besterarmor/Listeners/ArmorListener.java
> > > >   https://github.com/Civcraft/Bergeypvp/pull/5/files#diff-3 (143)
> > > > - _A_
> > > > 
> > > > src/com/valadian/bergecraft/besterarmor/Listeners/DecloakListener.java
> > > > https://github.com/Civcraft/Bergeypvp/pull/5/files#diff-4 (143)
> > > > - _A_
> > > > 
> > > > src/com/valadian/bergecraft/besterarmor/Listeners/HorseMountListener.java
> > > > https://github.com/Civcraft/Bergeypvp/pull/5/files#diff-5 (49)
> > > > - _A_
> > > >   src/com/valadian/bergecraft/besterarmor/Managers/ArmorManager.java
> > > >   https://github.com/Civcraft/Bergeypvp/pull/5/files#diff-6 (306)
> > > > 
> > > > Patch Links:
> > > > - https://github.com/Civcraft/Bergeypvp/pull/5.patch
> > > > - https://github.com/Civcraft/Bergeypvp/pull/5.diff
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/Civcraft/Bergeypvp/pull/5.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/Civcraft/Bergeypvp/pull/5#issuecomment-104892191.
> > 
> > ## 
> > 
> > Thank You,
> > Will Jackins
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Civcraft/Bergeypvp/pull/5#issuecomment-104946095.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Civcraft/Bergeypvp/pull/5#issuecomment-104946479.

## 

Thank You,
Will Jackins

**Comment by WildWeazel** [comment]
I'm very confused by the structure of this pull. Let's take a look at it here 06970298cf7225b45ea97b90adfed19b5692e5d5

@ttk2 It doesn't seem that bad, just something went wierd with the pull and it overrode the file history.

@valadian any thoughts?

**Pull request closed without merging**
